<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-06T12:10:50 IST" name="Default suite" finished-at="2022-06-06T12:13:08 IST" duration-ms="137664">
    <groups>
    </groups>
    <test started-at="2022-06-06T12:10:50 IST" name="Default test" finished-at="2022-06-06T12:13:08 IST" duration-ms="137664">
      <class name="SoFaDog.AndroidAutomation.DeleteAccountTest">
        <test-method is-config="true" signature="startService()[pri:0, instance:SoFaDog.AndroidAutomation.DeleteAccountTest@6babf3bf]" started-at="2022-06-06T12:10:50 IST" name="startService" finished-at="2022-06-06T12:11:03 IST" duration-ms="12530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startService -->
        <test-method is-config="true" signature="startDriver()[pri:0, instance:SoFaDog.AndroidAutomation.DeleteAccountTest@6babf3bf]" started-at="2022-06-06T12:11:03 IST" name="startDriver" finished-at="2022-06-06T12:11:35 IST" duration-ms="32589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:SoFaDog.AndroidAutomation.DeleteAccountTest@6babf3bf]" started-at="2022-06-06T12:11:35 IST" name="beforeMethod" finished-at="2022-06-06T12:11:35 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="DeleteAccountTestCase()[pri:0, instance:SoFaDog.AndroidAutomation.DeleteAccountTest@6babf3bf]" started-at="2022-06-06T12:11:35 IST" name="DeleteAccountTestCase" finished-at="2022-06-06T12:13:06 IST" duration-ms="90386" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User already exists] but found [AutoUser50]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User already exists] but found [AutoUser50]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at SoFaDog.AndroidAutomation.DeleteAccountTest.DeleteAccountTestCase(DeleteAccountTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteAccountTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:SoFaDog.AndroidAutomation.DeleteAccountTest@6babf3bf]" started-at="2022-06-06T12:13:06 IST" name="afterMethod" finished-at="2022-06-06T12:13:06 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:SoFaDog.AndroidAutomation.DeleteAccountTest@6babf3bf]" started-at="2022-06-06T12:13:06 IST" name="afterClass" finished-at="2022-06-06T12:13:06 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="stopService()[pri:0, instance:SoFaDog.AndroidAutomation.DeleteAccountTest@6babf3bf]" started-at="2022-06-06T12:13:06 IST" name="stopService" finished-at="2022-06-06T12:13:08 IST" duration-ms="2082" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopService -->
      </class> <!-- SoFaDog.AndroidAutomation.DeleteAccountTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
